Tue, 16 Apr 2019 22:36:00 driven_by_file.py[line:54] INFO 期望结果找到了！
Tue, 16 Apr 2019 22:36:08 driven_by_file.py[line:54] INFO 期望结果找到了！
Tue, 16 Apr 2019 22:36:16 driven_by_file.py[line:54] INFO 期望结果找到了！
Wed, 17 Apr 2019 10:03:51 driven_by_file.py[line:54] INFO 期望结果找到了！
Wed, 17 Apr 2019 10:04:02 driven_by_file.py[line:54] INFO 期望结果找到了！
Wed, 17 Apr 2019 10:04:15 driven_by_file.py[line:54] INFO 期望结果找到了！
Wed, 17 Apr 2019 10:20:55 driven_by_file.py[line:55] INFO 期望结果找到了！
Wed, 17 Apr 2019 10:21:06 driven_by_file.py[line:55] INFO 期望结果找到了！
Wed, 17 Apr 2019 10:21:17 driven_by_file.py[line:55] INFO 期望结果找到了！
Wed, 17 Apr 2019 10:23:51 driven_by_file.py[line:55] INFO 期望结果找到了！
Wed, 17 Apr 2019 10:24:00 driven_by_file.py[line:55] INFO 期望结果找到了！
Wed, 17 Apr 2019 10:24:08 driven_by_file.py[line:55] INFO 期望结果找到了！
Wed, 17 Apr 2019 10:24:46 driven_by_file.py[line:49] ERROR 页面没有找到！
Wed, 17 Apr 2019 10:25:15 driven_by_file.py[line:49] ERROR 页面没有找到！
Wed, 17 Apr 2019 10:25:42 driven_by_file.py[line:49] ERROR 页面没有找到！
Thu, 18 Apr 2019 12:30:42 driven_by_file.py[line:53] ERROR 其他异常！
Thu, 18 Apr 2019 12:37:27 driven_by_file.py[line:55] INFO 期望结果找到了！
Thu, 18 Apr 2019 12:37:38 driven_by_file.py[line:55] INFO 期望结果找到了！
Thu, 18 Apr 2019 12:37:49 driven_by_file.py[line:55] INFO 期望结果找到了！
